<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IngredienteSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('ingredientes')->insert([
            [
                'nombre'     => 'Pechuga de pollo',
                'unidad'     => 'unidad',
                'calorias'   => 165,
                'proteinas'  => 31,
                'grasas'     => 3.6,
                'carbohidratos' => 0,
            ],
            [
                'nombre'     => 'Arroz integral',
                'calorias'   => 111,
                'unidad'     => 'gramos',
                'proteinas'  => 2.6,
                'grasas'     => 0.9,
                'carbohidratos' => 23,
            ],
            [
                'nombre'     => 'Brócoli',
                'unidad'     => 'unidad',
                'calorias'   => 34,
                'proteinas'  => 2.8,
                'grasas'     => 0.4,
                'carbohidratos' => 7,
            ],
            [
                'nombre'        => 'Huevo',
                'unidad'        => 'unidad',
                'calorias'      => 72,
                'proteinas'     => 6.3,
                'grasas'        => 5.0,
                'carbohidratos' => 0.4,
            ],
            [
                'nombre'        => 'Leche entera',
                'unidad'        => 'ml',
                'calorias'      => 61,
                'proteinas'     => 3.2,
                'grasas'        => 3.3,
                'carbohidratos' => 4.8,
            ],
            [
                'nombre'        => 'Harina de trigo',
                'unidad'        => 'gramos',
                'calorias'      => 364,
                'proteinas'     => 10,
                'grasas'        => 1,
                'carbohidratos' => 76,
            ],
            [
                'nombre'        => 'Azúcar',
                'unidad'        => 'gramos',
                'calorias'      => 387,
                'proteinas'     => 0,
                'grasas'        => 0,
                'carbohidratos' => 100,
            ],
            [
                'nombre'        => 'Tomate',
                'unidad'        => 'unidad',
                'calorias'      => 22,
                'proteinas'     => 1.1,
                'grasas'        => 0.2,
                'carbohidratos' => 4.8,
            ],
            [
                'nombre'        => 'Lechuga',
                'unidad'        => 'unidad',
                'calorias'      => 15,
                'proteinas'     => 1.4,
                'grasas'        => 0.2,
                'carbohidratos' => 2.9,
            ],
            [
                'nombre'        => 'Zanahoria',
                'unidad'        => 'unidad',
                'calorias'      => 25,
                'proteinas'     => 0.6,
                'grasas'        => 0.1,
                'carbohidratos' => 6,
            ],
            [
                'nombre'        => 'Patata',
                'unidad'        => 'unidad',
                'calorias'      => 77,
                'proteinas'     => 2,
                'grasas'        => 0.1,
                'carbohidratos' => 17,
            ],
            [
                'nombre'        => 'Aceite de oliva',
                'unidad'        => 'ml',
                'calorias'      => 884,
                'proteinas'     => 0,
                'grasas'        => 100,
                'carbohidratos' => 0,
            ],
            [
                'nombre'        => 'Salmón',
                'unidad'        => 'gramos',
                'calorias'      => 208,
                'proteinas'     => 20,
                'grasas'        => 13,
                'carbohidratos' => 0,
            ],
            [
                'nombre'        => 'Atún en lata',
                'unidad'        => 'gramos',
                'calorias'      => 116,
                'proteinas'     => 26,
                'grasas'        => 1,
                'carbohidratos' => 0,
            ],
            [
                'nombre'        => 'Garbanzos cocidos',
                'unidad'        => 'gramos',
                'calorias'      => 164,
                'proteinas'     => 9,
                'grasas'        => 2.6,
                'carbohidratos' => 27,
            ],
            [
                'nombre'        => 'Queso cheddar',
                'unidad'        => 'gramos',
                'calorias'      => 403,
                'proteinas'     => 25,
                'grasas'        => 33,
                'carbohidratos' => 1.3,
            ],
            [
                'nombre'        => 'Manzana',
                'unidad'        => 'unidad',
                'calorias'      => 95,
                'proteinas'     => 0.5,
                'grasas'        => 0.3,
                'carbohidratos' => 25,
            ],
            [
                'nombre'        => 'Plátano',
                'unidad'        => 'unidad',
                'calorias'      => 105,
                'proteinas'     => 1.3,
                'grasas'        => 0.4,
                'carbohidratos' => 27,
            ],
            [
                'nombre'        => 'Yogur natural',
                'unidad'        => 'gramos',
                'calorias'      => 59,
                'proteinas'     => 10,
                'grasas'        => 0.4,
                'carbohidratos' => 4,
            ],
            [
                'nombre'        => 'Avena',
                'unidad'        => 'gramos',
                'calorias'      => 389,
                'proteinas'     => 17,
                'grasas'        => 7,
                'carbohidratos' => 66,
            ],
            [
                'nombre'        => 'Mantequilla',
                'unidad'        => 'gramos',
                'calorias'      => 717,
                'proteinas'     => 0.5,
                'grasas'        => 81,
                'carbohidratos' => 0.1,
            ],
            [
                'nombre'        => 'Espinacas',
                'unidad'        => 'gramos',
                'calorias'      => 23,
                'proteinas'     => 2.9,
                'grasas'        => 0.4,
                'carbohidratos' => 3.6,
            ],
            [
                'nombre'        => 'Cebolla',
                'unidad'        => 'unidad',
                'calorias'      => 44,
                'proteinas'     => 1.2,
                'grasas'        => 0.1,
                'carbohidratos' => 10,
            ],
        ]);
    }
}